name: ublue hwe 40
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '35 3 * * *'  # 3:30-ish UTC everyday (30 min delay after 'main' builds)
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 40